## <p style="color:blue"> Introduction to Jupyter Notebooks
Jupyter notebooks serve as a powerful tool for integrating executable code, code outputs, and text within a single cohesive file. These notebooks operate directly in a web browser, and interestingly, they do not necessitate an internet connection (unless you’re using a Jupyter Hub).

The **kernel** is the essential component responsible for executing your code. It acts as the bridge connecting the notebook interface (as you perceive it) to the computational resources on your local machine, where the actual code runs.

### <p style="color:blue"> Types of Cells

Jupyter Notebooks offer two types of cells: **Markdown** (like this one) and **Code**. Typically, you won’t execute the Markdown cells; instead, you’ll read their content. However, when you encounter a code cell, you’ll instruct Jupyter to run the code lines it contains.

Code cells are interpreted by the Python kernel. In other words, the Python interpreter executes whatever it recognizes as code within the cell.



In [65]:
# "#" in front of code is code annotation. The code is 
# not read by the computer.
# You can run a cell by pressing shift-enter.


### <p style="color:blue"> Formatting Markdown
Markdown is useful because it can be formatted using simple symbols. [Here's a full cheatsheet of markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for more tips, but the main syntax is below:
* Bulleted lists are created using asterisks.
* Numbered lists are created using numbers.
* You can **bold** with two asterisks or underscores on either side (`**bold**`) or *italicize* with one asterisk or underscore (`*italicize*`)
* Pound signs (#) create headers. More pound signs means a smaller header.


## <p style="color:red;">Exercise 1:
<p style="color:red;">Create a new markdown cell and write first name in the format heading 1 and your family name in the format heading 2. Under your first and last name, add a new line with your student id. Make sure that your student id is bold.</p>



### <p style="color:blue"> Automatic Code formatter
nb_black is a simple extension for Jupyter Notebook and Jupyter Lab to beautify Python code automatically.

# <p style="color:blue"> Introduction to Python 

### <p style="color:blue"> Order of Operations in Python

The order of operations is the same as in mathematics!

| Symbol |    Operation   | Usage |
|:------:|:--------------:|:-----:|
|    +   |    Addition    |  20+5 |
|    -   |   Subtraction  |  20-5 |
|    *   | Multiplication |  20*5 |
|    /   |    Division    |  20/5 |
|   **   |    Exponent    | 20**5 |
| %      |    Modulo      |  20%5 |

Note:
* If you want integer division, use // 

### <p style="color:blue"> Variables
Variables enable us to store a value and come back to it later. They are defined with `name = value`. *Assignment is not the same thing as equality,* as in mathematics.

### Types of Variables
Variables can be different types. Python lets you change the type of variables (the function is in parentheses below), however, *you cannot combine types*.

* Integers (`int`)
* String (`str`): letters, numbers, symbols, spaces
* Float (`float`): any number with a decimal point (floating point number)

You can check what type your variable is by using `type(variable)`.

If you ever need help using a function (e.g., `type`) in Jupyter Notebook, you can enter the function followed by a question mark or `help(function)`. For example, `type?` or `help(type)`.

Jupyter will only show you the output of the last line of code that you run. Thankfully, you can wrap commands in other commands. For example, we could write `print(type(a))`, if we want to see the output of `type(a)`.



In [66]:
a = 5

In [67]:
type(a)

int

In [68]:
print(type(a))

<class 'int'>


### <p style="color:blue"> Object Mutability
Reference: book Fluent Python, chapter 6: https://learning.oreilly.com/library/view/fluent-python-2nd/9781492056348/ch06.html#deep_x_shallow_copies

In [69]:
list_values = [1, 2, 3]  # creating a list
set_values = (1, 2, 3)  # creating a tuple
print(id(list_values))  # displays the unique identifier (memory address) 
# of the list
print(id(set_values), "\n")  # displays the unique identifier of the tuple

list_values += [4, 5, 6]  # appends the elements [4, 5, 6] to the existing list
set_values += (4, 5, 6)
# attempts to append the elements (4, 5, 6) to the existing tuple set_values.
# However, a new tuple and assigned to the name
# because tuples are immutable (cannot be modified after creation).
print(id(list_values))
print(id(set_values))

#Notice that the id is the same for the list but different for the tuple 

# In summary:

# Lists are mutable (you can modify their contents), 
# while tuples are immutable (you cannot modify their contents 
# after creation).
# The += operation works for lists (modifies the list in place), 
# but not for tuples.


2158205394816
2157697343360 

2158205394816
2158205034816


# <p style= color:blue>The Python Programming Language: Functions

**`add_numbers`** is a function that takes two numbers and adds them together

In [70]:
def add_numbers(x, y):
    return x + y

In [71]:
add_numbers(1, 2)

3

**add_numbers updated to take an optional 3rd parameter. Using print allows printing of multiple expressions within a single cell.**

In [72]:
def add_numbers(x, y, z=None):  # z is an optional parameter
    if z == None:
        return x + y
    else:
        return x + y + z


print(add_numbers(1, 2))

print(add_numbers(1, 2, 3))

3
6


# <p style= color:blue> Lambda comprehension
<br>A lambda function is a small anonymous function. It is like inline coding. A lambda function can take any number of arguments, but can only have one expression.
<br>
Here's an example of lambda that takes in three parameters and adds the first two.
    
These little, concise functions are quite handy when you need to define small, one-time-use functions without explicitly naming them
    
The basic syntax is: lambda arguments: expression  

Remember that lambda functions are limited to a single expression and cannot contain statements or complex logic.

In [73]:
my_function = lambda a, b, c: a + b

In [74]:
my_function(1, 2, 3)

3

## <p style="color:red;">Exercise 2:
<p style="color:red;"> a)Write a function that get a list of integers and append number 7 to the list. Print list values before and after calling function. 
<br> b) write a function that get a tuple of integeres and append number 7 to the tuple. Print the set values before and after calling function.)</p></br>

### Part a solution

### Part b solution

## <p style="color:red;">Exercise 3:
<p style="color:red;">
change the following function to a lamda function<br>
def my_fun(a):<br>
    &nbsp;&nbsp;&nbsp;&nbsp;return a**2<br>
my_fun(4)<br>

In [75]:
#Solution


# <p style=color:blue> The Python Programming Language: Create random list
    
    
%%time : Magic function that calculates the wall time that can be referred to as the total time required to execute that cell.

In [76]:
%%time  
#must be the first thing in the cell

import random

random_list = []
for i in range(1000):
    random_list.append(random.randint(0, 100))
    
#https://docs.python.org/3/library/random.html

print(random_list)

[61, 90, 20, 86, 93, 75, 98, 40, 43, 68, 27, 78, 73, 18, 90, 56, 0, 3, 56, 45, 92, 39, 85, 59, 98, 74, 52, 62, 48, 47, 87, 65, 48, 64, 64, 58, 72, 60, 25, 65, 77, 15, 4, 10, 53, 15, 41, 25, 18, 67, 58, 36, 84, 30, 12, 44, 52, 85, 13, 87, 29, 17, 96, 10, 86, 88, 6, 46, 95, 14, 6, 22, 55, 45, 26, 16, 44, 97, 67, 52, 50, 8, 58, 92, 6, 53, 53, 14, 59, 11, 66, 24, 62, 37, 90, 79, 59, 69, 98, 27, 34, 17, 51, 13, 97, 92, 58, 0, 16, 71, 83, 6, 54, 57, 100, 61, 23, 62, 76, 21, 94, 40, 87, 73, 91, 12, 21, 93, 4, 18, 23, 89, 75, 54, 24, 92, 41, 10, 23, 11, 37, 35, 29, 41, 65, 50, 48, 79, 57, 7, 62, 27, 79, 71, 16, 59, 62, 77, 100, 99, 74, 99, 35, 73, 31, 66, 97, 1, 83, 45, 96, 53, 71, 86, 8, 23, 80, 67, 27, 31, 22, 100, 90, 17, 82, 76, 77, 36, 48, 46, 46, 62, 70, 27, 37, 17, 57, 9, 91, 50, 61, 82, 71, 39, 67, 78, 86, 91, 13, 66, 50, 71, 60, 85, 96, 15, 66, 74, 50, 89, 25, 80, 6, 47, 73, 20, 56, 73, 2, 59, 28, 35, 54, 60, 49, 31, 42, 57, 22, 70, 38, 17, 85, 8, 55, 42, 2, 49, 17, 49, 45, 75, 5, 5, 

In [77]:
# iterate over list
for i in random_list:
    print(i)

61
90
20
86
93
75
98
40
43
68
27
78
73
18
90
56
0
3
56
45
92
39
85
59
98
74
52
62
48
47
87
65
48
64
64
58
72
60
25
65
77
15
4
10
53
15
41
25
18
67
58
36
84
30
12
44
52
85
13
87
29
17
96
10
86
88
6
46
95
14
6
22
55
45
26
16
44
97
67
52
50
8
58
92
6
53
53
14
59
11
66
24
62
37
90
79
59
69
98
27
34
17
51
13
97
92
58
0
16
71
83
6
54
57
100
61
23
62
76
21
94
40
87
73
91
12
21
93
4
18
23
89
75
54
24
92
41
10
23
11
37
35
29
41
65
50
48
79
57
7
62
27
79
71
16
59
62
77
100
99
74
99
35
73
31
66
97
1
83
45
96
53
71
86
8
23
80
67
27
31
22
100
90
17
82
76
77
36
48
46
46
62
70
27
37
17
57
9
91
50
61
82
71
39
67
78
86
91
13
66
50
71
60
85
96
15
66
74
50
89
25
80
6
47
73
20
56
73
2
59
28
35
54
60
49
31
42
57
22
70
38
17
85
8
55
42
2
49
17
49
45
75
5
5
94
91
94
27
48
69
10
54
93
94
56
99
17
38
41
47
6
44
16
52
41
42
98
34
96
68
15
59
93
51
57
64
42
88
85
25
96
71
19
100
2
84
22
22
64
24
32
76
86
55
60
4
26
12
88
43
84
52
53
91
70
100
12
14
64
9
52
38
69
48
89
72
38
36
49
6
10
31
27
59
52
39
12
84
47
94


In [78]:
# iterate by index
for i in range(len(random_list)):
    print(random_list[i])

61
90
20
86
93
75
98
40
43
68
27
78
73
18
90
56
0
3
56
45
92
39
85
59
98
74
52
62
48
47
87
65
48
64
64
58
72
60
25
65
77
15
4
10
53
15
41
25
18
67
58
36
84
30
12
44
52
85
13
87
29
17
96
10
86
88
6
46
95
14
6
22
55
45
26
16
44
97
67
52
50
8
58
92
6
53
53
14
59
11
66
24
62
37
90
79
59
69
98
27
34
17
51
13
97
92
58
0
16
71
83
6
54
57
100
61
23
62
76
21
94
40
87
73
91
12
21
93
4
18
23
89
75
54
24
92
41
10
23
11
37
35
29
41
65
50
48
79
57
7
62
27
79
71
16
59
62
77
100
99
74
99
35
73
31
66
97
1
83
45
96
53
71
86
8
23
80
67
27
31
22
100
90
17
82
76
77
36
48
46
46
62
70
27
37
17
57
9
91
50
61
82
71
39
67
78
86
91
13
66
50
71
60
85
96
15
66
74
50
89
25
80
6
47
73
20
56
73
2
59
28
35
54
60
49
31
42
57
22
70
38
17
85
8
55
42
2
49
17
49
45
75
5
5
94
91
94
27
48
69
10
54
93
94
56
99
17
38
41
47
6
44
16
52
41
42
98
34
96
68
15
59
93
51
57
64
42
88
85
25
96
71
19
100
2
84
22
22
64
24
32
76
86
55
60
4
26
12
88
43
84
52
53
91
70
100
12
14
64
9
52
38
69
48
89
72
38
36
49
6
10
31
27
59
52
39
12
84
47
94


In [79]:
# check if a number is in the list
if 65 in random_list:
    print("True")

True


In [80]:
# You can call list items by list[first_index:last_index:step]
# print list from index 6 to 16
random_list[6:16]

[98, 40, 43, 68, 27, 78, 73, 18, 90, 56]

In [81]:
# print the last 10 item in the list
random_list[-10:]

[45, 93, 48, 64, 39, 81, 66, 59, 74, 6]

In [82]:
# print the items 6 to 16, but even indexes
random_list[6:16:2]

[98, 43, 27, 73, 90]

# <p style=color:blue>  The Python Programming Language: Numerical Python (NumPy)

In [83]:
import numpy as np

## <p style=color:blue> Creating Arrays

**Create a list and convert it to a numpy array**

In [84]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

**Or just pass in a list directly**

In [85]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

**Pass in a list of lists to create a multidimensional array.**

In [86]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

**Use the shape method to find the dimensions of the array. (rows, columns)**

In [87]:
m.shape

(2, 3)

**`arange` returns evenly spaced values within a given interval.**

In [88]:
n = np.arange(0, 30, 2)  # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

**`reshape` returns an array with the same data with a new shape.**

In [89]:
n = n.reshape(3, 5)  # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])


**`linspace` returns evenly spaced numbers over a specified interval.**

In [90]:
o = np.linspace(0, 4, 9)  # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

**`resize` changes the shape and size of array in-place.**

In [91]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

**`ones` returns a new array of given shape and type, filled with ones.**

In [92]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

**`zeros` returns a new array of given shape and type, filled with zeros.**

In [93]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.**

In [94]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


**`diag` extracts a diagonal or constructs a diagonal array.**

In [95]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

**Create an array using repeating list**

In [96]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

**Repeat elements of an array using `repeat`.**

In [97]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Combining Arrays

In [98]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

**Use `vstack` to stack arrays in sequence vertically (row wise).**

In [99]:
np.vstack([p, 2 * p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

**Use `hstack` to stack arrays in sequence horizontally (column wise).**

In [100]:
np.hstack([p, 2 * p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## <p style= color:blue> Numerical Operations on Arrays

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [101]:
print(x + y)  # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y)  # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [102]:
print(x * y)  # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y)  # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [103]:
print(x**2)  # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>

**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

<br>

In [104]:
x.dot(y)  # dot product  1*4 + 2*5 + 3*6

32

In [107]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [27]:
z.shape

(2, 3)

In [28]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

The shape of array `z` is `(2,3)` before transposing.





**Use `.T` to get the transpose**

In [29]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [30]:
z.T.shape

(3, 2)

The number of rows has swapped with the number of columns.


<br>


**Use `.dtype` to see the data type of the elements in the array.**

In [31]:
z.dtype

dtype('int32')

<br>

**Use `.astype` to cast to a specific type.**

In [32]:
z = z.astype("f")
z.dtype

dtype('float32')

<br>



### <p style=color:blue> Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [33]:
a = np.array([-4, -2, 1, 3, 5])

In [34]:
a.sum()

3

In [35]:
a.max()

5

In [36]:
a.min()

-4

<br>

**`argmax` and `argmin` return the index of the maximum and minimum values in the array.**

In [37]:
a.argmax()

4

In [38]:
a.argmin()

0

In [39]:
a.mean()

0.6

In [40]:
a.std()  # note that the numpy std function uses the equation for population std

3.2619012860600183

<br>

### <p style=color:blue> Array Indexing / Slicing

In [41]:
s = np.arange(13) ** 2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>

**Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.**

In [42]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>

**Use `:` to indicate a range. `array[start:stop]`**


**Leaving `start` or `stop` empty will default to the beginning/end of the array.**

In [43]:
s[1:5]

array([ 1,  4,  9, 16])

**Use negatives to count from the back.**

In [44]:
s[-4:]

array([ 81, 100, 121, 144])

<br>

**A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`**

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [45]:
s[-5::-2]

array([64, 36, 16,  4,  0])


**Let's look at a multidimensional array.**

In [46]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use bracket notation to slice: `array[row, column]`

In [47]:
r[2, 2]

14


And use `:` to select a range of rows or columns

In [48]:
r[3, 3:6]

array([21, 22, 23])

Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [49]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [50]:
r[-1, ::2]

array([30, 32, 34])

**We can also perform conditional indexing.**

Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [51]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [52]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>

## <p style=color:blue>  Copying Data

<p style=color:purple> Be careful with copying and modifying arrays in NumPy!

r2 is a slice of r

In [53]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])


Set this slice's values to zero ([:] selects the entire array)

In [54]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])


`r` has also been changed!

In [55]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])


<p style=color:purple> To avoid this, use `r.copy` to create a copy that will not affect the original array

In [56]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])


**Now when r_copy is modified, r will not be changed.**

In [57]:
r_copy[:] = 10
print(r_copy, "\n")
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]



### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [58]:
test = np.random.randint(0, 10, (4, 3))
test

array([[2, 7, 7],
       [3, 7, 4],
       [8, 3, 6],
       [8, 5, 9]])


#### Iterate by row:

In [59]:
for row in test:
    print(row)

[2 7 7]
[3 7 4]
[8 3 6]
[8 5 9]



#### Iterate by index:

In [60]:
for i in range(len(test)):
    print(test[i])

[2 7 7]
[3 7 4]
[8 3 6]
[8 5 9]


#### Iterate by row and index:

In [61]:
for i, row in enumerate(test):
    print("row", i, "is", row)

row 0 is [2 7 7]
row 1 is [3 7 4]
row 2 is [8 3 6]
row 3 is [8 5 9]


**Use `zip` to iterate over multiple iterables.**

In [62]:
test2 = test**2
test2

array([[ 4, 49, 49],
       [ 9, 49, 16],
       [64,  9, 36],
       [64, 25, 81]])

In [63]:
for i, j in zip(test, test2):
    print(i, "+", j, "=", i + j)

[2 7 7] + [ 4 49 49] = [ 6 56 56]
[3 7 4] + [ 9 49 16] = [12 56 20]
[8 3 6] + [64  9 36] = [72 12 42]
[8 5 9] + [64 25 81] = [72 30 90]


#### <p style="color:red;"> Exersise 4:
<p style="color:red;"> a)Create a numpy array of 20 items all 1 and name it A<br> b)Rearrange it by 4 rows and 5 columns
<br> c)Create a numpy array of 5 random numbers and name it B<br> d)Replace the last row of array A with B
<br> e)Do dot multiple of A with B and save it in a new array called C<br> f)Print every row of the array C by iterating every row<br> 