## <p style="color:red;">Exercise 1:
<p style="color:red;">Create a new markdown cell and write first name in the format heading 1 and your family name in the format heading 2. Under your first and last name, add a new line with your student id. Make sure that your student id is bold.</p>



### <span style="color:rgb(39, 190, 228);">**Exercise 1 Solution**</span>

# <span style="color: #800080;">Jonathan</span> 
## <span style="color: #A259C4;">Marien</span>
### <span style="color: #C49DDC;">991476393</span>

## <p style="color:red;">Exercise 2:
<p style="color:red;"> a)Write a function that get a list of integers and append number 7 to the list. Print list values before and after calling function. 
<br> b) write a function that get a tuple of integeres and append number 7 to the tuple. Print the set values before and after calling function.)</p></br>

### <span style="color:rgb(39, 190, 228);">**Exercise 2 Solution**</span>

#### <span style="color:rgb(128, 238, 246);">**Part A Solution**</span>

In [ ]:
## Exercise 2:
### a)Write a function that get a list of integers and append number 7 to the list. Print list values before and after calling function. 

In [ ]:
def append_seven(int_list):
    """
    Appends the integer 7 to the provided list.

    Parameters:
        int_list (list of int): The list to which the integer 7 will be appended.

    Returns:
        None. The input list is modified in place.
    """
    int_list.append(7)

my_list = [1, 2, 3, 4]
print("Before:", my_list)
append_seven(my_list)
print("After:", my_list)

Before: [1, 2, 3, 4]
After: [1, 2, 3, 4, 7]


#### <span style="color:rgb(128, 238, 246);">**Part B Solution**</span>

In [ ]:
## Exercise 2:
### b) write a function that get a tuple of integeres and append number 7 to the tuple. Print the set values before and after calling function.)

In [ ]:
def append_seven_to_tuple(int_tuple):
    """
    Appends the integer 7 to the end of a given tuple.

    Parameters:
        int_tuple (tuple): A tuple of integers.

    Returns:
        tuple: A new tuple with the number 7 added at the end.
    """
    return int_tuple + (7,)

# Tuples are immutable, so to "add" an element, create a new tuple with the additional value and reassign it.
# This is done by concatenating the original tuple with another tuple containing the new element (e.g., 7).
my_tuple = (1, 2, 3, 4)
print("Before:", my_tuple)
my_tuple = append_seven_to_tuple(my_tuple)
print("After:", my_tuple)

Before: (1, 2, 3, 4)
After: (1, 2, 3, 4, 7)


## <p style="color:red;">Exercise 3:
<p style="color:red;">
change the following function to a lamda function<br>
def my_fun(a):<br>
    &nbsp;&nbsp;&nbsp;&nbsp;return a**2<br>
my_fun(4)<br>

### <span style="color: rgb(39, 190, 228);">**Exercise 3 Solution**</span>

In [ ]:
## Exercise 3: change the above function to be a lambda function
my_fun = lambda a: a**2  # noqa: E731 - disables warnings about using def over lambda
my_fun(4)

16

#### <p style="color:red;"> Exersise 4:
<p style="color:red;"> a)Create a numpy array of 20 items all 1 and name it A<br> b)Rearrange it by 4 rows and 5 columns
<br> c)Create a numpy array of 5 random numbers and name it B<br> d)Replace the last row of array A with B
<br> e)Do dot multiple of A with B and save it in a new array called C<br> f)Print every row of the array C by iterating every row<br> 

### <span style="color: rgb(39, 190, 228);">**Exercise 4 Solution**</span>

In [ ]:
import numpy as np

# a) Create a numpy array of 20 items all 1 and name it A
A = np.ones(20)
#print(A) -- test printing each step to make sure it works

# b) Rearrange it by 4 rows and 5 columns
A = A.reshape(4, 5)
#print(A)

# c) Create a numpy array of 5 random numbers and name it B
B = np.random.rand(5)
#print(B)

# d) Replace the last row of array A with B
A[-1] = B
#print(A)

# e) Do dot multiple of A with B and save it in a new array called C
C = np.dot(A, B)
#print(C)

# f) Print every row of the array C by iterating every row
for i in C:
    print(i)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0.61999696 0.60586357 0.37863709 0.36040259 0.61280988]
[[1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.61999696 0.60586357 0.37863709 0.36040259 0.61280988]]
[2.57771009 2.57771009 2.57771009 1.40025891]
2.5777100877550816
2.5777100877550816
2.5777100877550816
1.4002589125872749


In [ ]:
# Visualization of Exercise 4 -- without saving to variables
import numpy as np

# np.ones(20).reshape(4, 5)

# np.random.rand(5)

np.dot(np.ones(20).reshape(4, 5), np.random.rand(5))


array([2.48746768, 2.48746768, 2.48746768, 2.48746768])